export const neighborhoodsByCity = {
  "Abreu e Lima": [
    "Alto da Bela Vista",
    "Alto São Miguel",
    "Caetés",
    "Caetés I",
    "Caetés II",
    "Caetés III",
    "Caiana",
    "Centro",
    "Desterro",
    "Engenho Novo",
    "Fosfato",
    "Inhamã",
    "Matinha",
    "Pitangas",
    "Planalto",
    "São Bento",
    "Timbó",
  ],
  Araçoiaba: [
    "Centro",
    "Loteamento Bom Jesus",
    "Loteamento Esperança",
    "Loteamento Flores",
    "Nova Araçoiaba",
    "Quinze",
    "Vila Itapipiré",
  ],
  "Cabo de Santo Agostinho": [
    "Alto da Bela Vista",
    "Banda Baixa",
    "Bom Conselho",
    "Centro",
    "Charneca",
    "Charnequinha",
    "Cohab",
    "Destilaria",
    "Distrito Industrial Diper",
    "Distrito Industrial Santo Estevão",
    "Enseada dos Corais",
    "Engenho Ilha",
    "Gaibu",
    "Garapu",
    "Itapuama",
    "Jardim Santo Inácio",
    "Malaquias",
    "Mercês",
    "Paiva",
    "Pirapama",
    "Ponte dos Carvalhos",
    "Pontezinha",
    "Rosário",
    "São Francisco",
    "Santo Agostinho",
    "Suape",
    "Vila Pirapama",
    "Vila Roca",
    "Vila Social Contra Mocambo",
  ],
  Camaragibe: [
    "Alberto Maia",
    "Aldeia de Baixo",
    "Aldeia dos Camarás",
    "Alto da Boa Vista",
    "Alto Santo Antonio",
    "Areeiro",
    "Bairro dos Estados",
    "Bairro Novo do Carmelo",
    "Borralho",
    "Céu Azul",
    "Celeiro das Alegrias Futuras",
    "Estação Nova",
    "João Paulo II",
    "Jardim Primavera",
    "Nazaré",
    "Oitenta",
    "Santa Mônica",
    "Santa Tereza",
    "Santana",
    "São João e São Paulo",
    "São Paulo",
    "São Pedro",
    "Tabatinga",
    "Timbí",
    "Vale das Pedreiras",
    "Vera Cruz",
    "Viana",
    "Vila da Fábrica",
    "Vila da Inabi",
  ],
  Igarassu: [
    "Agamenon Magalhães",
    "Alto do Céu",
    "Ana de Albuquerque",
    "Área Rural de Igarassu",
    "Bela Vista",
    "Bonfim",
    "Campina de Feira",
    "Centro",
    "Cruz do Rebouças",
    "Encanto Igarassu",
    "Inhamã",
    "Jabacó",
    "Jardim Boa Sorte",
    "Monjope",
    "Pancó",
    "Posto de Monta",
    "Rubina",
    "Santa Luzia",
    "Santa Rita",
    "Santo Antônio",
    "Saramandaia",
    "Sítio dos Marcos",
    "Tabatinga",
    "Triunfo",
    "Umbura",
    "Vila Rural",
  ],
  "Ilha de Itamaracá": ["Baixa Verde"],
  Ipojuca: [
    "Camela",
    "Centro",
    "Distrito de Camela",
    "Nossa Senhora do Ó",
    "Porto de Galinhas",
    "Suape",
  ],
  Itapissuma: ["Centro"],
  "Jaboatão dos Guararapes": [
    "Área Rural de Jaboatão dos Guararapes",
    "Barra de Jangada",
    "Bulhões",
    "Cajueiro Seco",
    "Candeias",
    "Cavaleiro",
    "Centro",
    "Comportas",
    "Curado",
    "Dois Carneiros",
    "Engenho Velho",
    "Floriano",
    "Guararapes",
    "Jardim Jordão",
    "Manassu",
    "Marcos Freire",
    "Muribeca",
    "Muribeca dos Guararapes",
    "Muribequinha",
    "Piedade",
    "Prazeres",
    "Santana",
    "Santo Aleixo",
    "Socorro",
    "Sucupira",
    "Vargem Fria",
    "Vila Rica",
    "Vista Alegre",
    "Zumbi do Pacheco",
  ],
  Moreno: ["Centro"],
  Olinda: [
    "Águas Compridas",
    "Aguazinha",
    "Alto da Bondade",
    "Alto da Conquista",
    "Alto da Nação",
    "Alto Sol Nascente",
    "Amaro Branco",
    "Amparo",
    "Área Rural de Olinda",
    "Bairro Novo",
    "Bonsucesso",
    "Bultrins",
    "Caixa D'Água",
    "Carmo",
    "Casa Caiada",
    "Fragoso",
    "Guadalupe",
    "Jardim Atlântico",
    "Jardim Brasil",
    "Monte",
    "Ouro Preto",
    "Passarinho",
    "Peixinhos",
    "Rio Doce",
    "Salgadinho",
    "Santa Tereza",
    "São Benedito",
    "Sapucaia",
    "Sítio Novo",
    "Tabajara",
    "Umuarama",
    "Varadouro",
    "Vila Popular",
  ],
  Paulista: [
    "Área Rural de Paulista",
    "Arthur Lundgren I",
    "Arthur Lundgren II",
    "Centro",
    "Engenho Maranguape",
    "Fragoso",
    "Jaguarana",
    "Jaguaribe",
    "Janga",
    "Jardim Maranguape",
    "Jardim Paulista",
    "Maranguape I",
    "Maranguape II",
    "Maria Farinha",
    "Mirueira",
    "Nobre",
    "Nossa Senhora da Conceição",
    "Nossa Senhora do Ó",
    "Paratibe",
    "Pau Amarelo",
    "Poty",
    "Tabajara",
    "Vila Torres Galvão",
  ],
  Recife: [
    "Aflitos",
    "Afogados",
    "Água Fria",
    "Alto José Bonifácio",
    "Alto José do Pinho",
    "Alto Santa Terezinha",
    "Alto do Mandu",
    "Apipucos",
    "Área Rural de Recife",
    "Areias",
    "Arruda",
    "Barro",
    "Beberibe",
    "Boa Viagem",
    "Boa Vista",
    "Bomba do Hemetério",
    "Bongi",
    "Brasília Teimosa",
    "Brejo da Guabiraba",
    "Brejo de Beberibe",
    "Cabanga",
    "Caçote",
    "Cajueiro",
    "Campina do Barreto",
    "Campo Grande",
    "Casa Amarela",
    "Casa Forte",
    "Caxangá",
    "Cidade Universitária",
    "Coelhos",
    "COHAB",
    "Coqueiral",
    "Cordeiro",
    "Córrego do Jenipapo",
    "Curado",
    "Derby",
    "Dois Irmãos",
    "Dois Unidos",
    "Encruzilhada",
    "Engenho do Meio",
    "Espinheiro",
    "Estância",
    "Fundão",
    "Graças",
    "Guabiraba",
    "Hipódromo",
    "Ibura",
    "Ilha Joana Bezerra",
    "Ilha do Leite",
    "Ilha do Retiro",
    "Imbiribeira",
    "Ipsep",
    "Iputinga",
    "Jaqueira",
    "Jardim São Paulo",
    "Jiquiá",
    "Jordão",
    "Linha do Tiro",
    "Macaxeira",
    "Madalena",
    "Mangabeira",
    "Mangueira",
    "Monteiro",
    "Morro da Conceição",
    "Mustardinha",
    "Nova Descoberta",
    "Paissandu",
    "Parnamirim",
    "Passarinho",
    "Peixinhos",
    "Pina",
    "Poço",
    "Ponto de Parada",
    "Porto da Madeira",
    "Prado",
    "Recife",
    "Rosarinho",
    "San Martin",
    "Sancho",
    "Santana",
    "Santo Amaro",
    "Santo Antônio",
    "São José",
    "Sítio dos Pintos",
    "Soledade",
    "Tamarineira",
    "Tejipió",
    "Torre",
    "Torreão",
    "Torrões",
    "Totó",
    "Várzea",
    "Vasco da Gama",
    "Zumbi",
  ],
  "São Lourenço da Mata": [
    "Área Rural de São Lourenço da Mata",
    "Capibaribe",
    "Centro",
    "Chã da Tábua",
    "Muribara",
    "Nova Tiúma",
    "Parque Capibaribe",
    "Penedo",
    "Pixete",
    "Tiúma",
  ],
  all: ["Todos"],
} as const;
